apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: archie-web-db
  namespace: archie
spec:
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      app: archie-db
  template:
    metadata:
      labels:
        app: archie-db 
    spec:
      containers:
        - name: archie-db 
          image: mysql:9.2
          env:
            - name: MYSQL_ONETIME_PASSWORD
              value: "yes"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-root-login
                  key: pass
            - name: MYSQL_USER
              valueFrom: 
                secretKeyRef:
                  name: db-login
                  key: db-user
            - name: MYSQL_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: db-login  # secret name
                  key: db-pass    
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-vol
              mountPath: /var/lib/mysql
      volumes:
        - name: db-vol
          #persistentVolumeClaim:
          #  claimName: archie-db-pvc
          emptyDir:
            sizeLimit: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: svr-db
  namespace: archie 
spec:
  selector:
    app: archie-db
  clusterIP: None
  ports:
  - protocol: TCP
    port: 3306

