apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: archie-cert
  namespace: archie
spec:
  # Secret names are always required.
  secretName: archie-tls-auto
  dnsNames: 
    - archie.zapto.org
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
