# this exists solely to load data into the CephFS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-loader 
  namespace: archie
  labels:
    app: ceph-loader
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ceph-loader 
  template:
    metadata:
      labels:
        app: ceph-loader
    spec:
      containers:
      - name: loader 
        image: debian
        imagePullPolicy: IfNotPresent
        command: [ "sleep", "infinity" ]
        volumeMounts:
        - name: jf-fs
          mountPath: /jf-vol
      volumes:
      - name: jf-fs
        persistentVolumeClaim:
          claimName: jellyfin-ceph-pvc
          readOnly: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - archie
