apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: main-ceph-fs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - name: main-ceph-fs-replicated
      replicated:
        size: 3
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
