apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        ports:
        - containerPort: 8096
      volumes:
      - name: config
        configMap:
          name: jellyfin-cfg
      - name: media
        persistentVolumeClaim:
          claimName: jellyfin-media-pvc
