
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-ceph-pvc
  namespace: archie
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Gi
