# from Kubernetes Docs:
# https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/storage/storageclass/storageclass-local.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner # indicates that this StorageClass does not support automatic provisioning
volumeBindingMode: WaitForFirstConsumer
